### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by ai** [steveblue/rollup-plugin-inline-postcss#1]
Tests are very important for every open source project

**Comment by steveblue** [comment]
For sure @ai! Tests are on the horizon very soon for this plugin.

**Comment by steveblue** [comment]
Initial test is on the master branch. Will update with more tests over time.

**Comment by steveblue** [comment]
Thanks for posting this awhile back @ai. Ever since testing has gotten way better in this repo. Github Actions. 💪
