### ISSUE TITLE
Throw error when the `postcss.config.js` file exporting an object, but not a function

### ISSUE THREAD

**Issue by fengyuanchen** [steveblue/rollup-plugin-inline-postcss#13]
https://github.com/steveblue/rollup-plugin-inline-postcss/blob/9e11867db5a7ad0ddbd3023d0c53cd9d14a1c386/index.ts#L38

**Comment by steveblue** [comment]
This has been fixed on master, the next release should support Object or Function in postcss.config.js.

**Comment by steveblue** [comment]
Fixed in 3.0.0
