### ISSUE TITLE
Only transform the first matched style segment, but skip all other style segments when a JS file contains more than one style segment

### ISSUE THREAD

**Issue by fengyuanchen** [steveblue/rollup-plugin-inline-postcss#14]
https://github.com/steveblue/rollup-plugin-inline-postcss/blob/9e11867db5a7ad0ddbd3023d0c53cd9d14a1c386/index.ts#L41

**Comment by steveblue** [comment]
Just want to verify the ask here @fengyuanchen. You want the plugin to support multiple style segments? I think that's a reasonable ask.

**Comment by fengyuanchen** [comment]
Yes. When process the output file bundled from multiple JS modules, there may be multiple style segments in the file.

**Comment by steveblue** [comment]
This change is potentially breaking and may require a major version bump. This feature is currently implemented on master.

**Comment by steveblue** [comment]
Fixed in 3.0.0

**Comment by steveblue** [comment]
@fengyuanchen any feedback on the latest implementation? 3.0.0+ should support multiple style declarations.

**Comment by fengyuanchen** [comment]
Works fine now👍
