### ISSUE TITLE
Missing documentation for the `escapeTemplateString` option

### ISSUE THREAD

**Issue by fengyuanchen** [steveblue/rollup-plugin-inline-postcss#15]
https://github.com/steveblue/rollup-plugin-inline-postcss/blob/9e11867db5a7ad0ddbd3023d0c53cd9d14a1c386/index.ts#L42

**Comment by steveblue** [comment]
This option may be deprecated in the next release. Still testing, but I think it may not be needed anymore.

**Comment by steveblue** [comment]
`escapeTemplateString` deprecated in 3.0.0
