### ISSUE TITLE
You're not really allowing custom regex

### ISSUE THREAD

**Issue by CKGrafico** [steveblue/rollup-plugin-inline-postcss#2]
Hello and thank you for this plugin :D

I'm opening this issue because I think taht you're breaking custom regex in this line:
```
const css = code.match(styleRegex)[0].split("`")[1];
```

I've changed my regex to:
```
/<style>((?:\\.|[^"\\])*)</style>/g
```

to work on these kind of files:
```
    <hero-part></hero-part>
      <h1>${title}</h1>
      <footer-part></footer-part>
    </main>

    <style>
      html,
      body {
        color: red;
     }
   </syle>
```

And is not able to do the 'split', 

For other devs looking for help, to work on my project I had to do that:

```
replace({
      '<style>': 'css`',
      '</style>': '` /* style */',
      delimiters: ['', ''],
    }),
    postcssInline({
      plugins: [postcssNested, postcssAutoprefixer],
    }),
    replace({
      'css`': '<style>',
      '` /* style */': '</style>',
      delimiters: ['', ''],
    }),
```

**Comment by steveblue** [comment]
Ack! Thanks for reporting!

**Comment by steveblue** [comment]
Please try your custom regex with `2.0.0`, which also now supports postcss 8.0.0 @CKGrafico

**Comment by CKGrafico** [comment]
Thanks for your time :D

**Comment by steveblue** [comment]
^3.0.0 further enhances how custom RexExp can be declared. Using the above example, you could do:

```
inlinePostCSS({
  styleRegex: /(?:<style>)((.|\n)+?)(?=(<\/style>))/gi,
  styleDelimiter: /<\/?style>/g,
});
```
and no further configuration should be needed with `replace`.
